import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";



export const metadata: Metadata = {
  title: "Tefsir App",
  description: "Generated by Poland Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
